- README.md
- openapi_tester/clients.py
- openapi_tester/constants.py
- openapi_tester/loaders.py
- openapi_tester/schema_tester.py
- test_project/api/serializers.py
- test_project/api/views/pets.py
- test_project/urls.py
- tests/conftest.py
- tests/schemas/openapi_v3_reference_schema.yaml
- tests/test_clients.py
- tests/test_errors.py
- tests/test_schema_tester.py
- tests/test_validators.py
issue: https://github.com/snok/drf-openapi-tester/issues/291
Currently, the package offers the possibility of validating only the response, however, it is useful to also at the same time,e to have validated that the passed `resquestBody` in our functional tests are also properly documented and match the implementation.
- Methods for validating request (`validate_request`) and extract the corresponding `requestBody` schema section from the OpenAPI schema (`get_request_body_schema_section`)
- Updating `test_project` to also expose `Pets` API, as it is the OpenAPI schema we have in tests.
- Adding tests for schema tester, clients and validators.
- Updating affected variables and functions.
- Adding support **only** for `openapi` schemas (no `swagger`, previous versions), which involves …
> feat: adding support for request validation

- .github/workflows/publish.yml
Updating publish workflow to use newly created `maticardenas` common `.github` files.
> chore: updating publish workflow

- .github/workflows/publish.yml
After renaming package, enabling `publish` stage for actual `PyPi` repository.
> feat: enabling publish to pypi

- CHANGELOG.md
- README.md
- openapi_tester/__init__.py
- poetry.lock
- pyproject.toml
Renaming to `django-contract-tester` as more generic name with which foresee a greater scopre for the package
> Rename to django contract tester

- README.md
- openapi_tester/__init__.py
- openapi_tester/case_testers.py
- openapi_tester/clients.py
- openapi_tester/constants.py
- openapi_tester/loaders.py
- openapi_tester/response_handler.py
- openapi_tester/schema_tester.py
- openapi_tester/utils.py
- openapi_tester/validators.py
- pyproject.toml
- test_project/api/ninja/api.py
- tests/conftest.py
- tests/schema_converter.py
- tests/schemas/openapi_v3_prefix_in_server.yaml
- tests/test_django_ninja.py
- tests/test_schema_tester.py
Introducing support for passing a `path_prefix` to `SchemaTester` class. 
In some cases where many APIs shared the same path prefix (e.g. `api/v1/`), it could be that this is included in the server URL to avoid repetition. 
Given this prefix might be part of the `urls` paths defined in Django, it leads to the library to not find the corresponding paths in the schema (e.g. url path in django `/api/v1/pets` while in the schema the path is just `/pets`). 
This PR adds a new argument to allow passing a prefix to match with django paths, in case this one is appended in the `server` url of the OpenAPI specification.
> feat: introducing path prefix support for SchemaTester

- openapi_tester/clients.py
- openapi_tester/config.py
- openapi_tester/constants.py
- openapi_tester/schema_tester.py
- openapi_tester/validators.py
- test_project/api/serializers.py
- tests/conftest.py
- tests/schema_converter.py
- tests/schemas/openapi_v3_reference_schema.yaml
- tests/test_clients.py
- tests/test_django_ninja.py
- tests/test_errors.py
- tests/test_schema_tester.py
Currently, the error messages make the debugging hard, as it is difficult to figure out where are there issues (in the request or the documentation), for which request it is happening and what's the exact problem and the expectation.
This PR aims to fix that (partially) by changing a few things:
1. Change how the reference is created: 
The existing reference contained minimal information and it also had a bug where it would continuously attach fields to it, even when it should have pointed to only one field. The new format will contain informations about the request path and type, if it's the request or response, and the drilldowned path to the key with the issues (if it's the case)
The new format will look like this: '`<request_type>` `<request_path>` > `<request/response>` > …
> feat: update error messages

- openapi_tester/schema_tester.py
My test case failed because of `TypeError: Object of type date is not JSON serializable` .
> fix: date not json serializable

- README.md
- openapi_tester/clients.py
- openapi_tester/response_handler.py
- openapi_tester/response_handler_factory.py
- openapi_tester/schema_tester.py
- openapi_tester/utils.py
- pyproject.toml
- test_project/api/serializers.py
- tests/conftest.py
- tests/test_clients.py
- tests/test_django_framework.py
- tests/test_django_ninja.py
- tests/test_schema_tester.py
- tests/utils.py
As specified in [Django Ninja documentation](https://django-ninja.dev/guides/testing/), despite being compatible with Django Test Client, using Django Ninja Test Client for Django Ninja APIs ends up being more efficient and faster. Adding therefore support for it in this PR, so that django ninja projects, which already use ninja test client, can switch smoothly to the new client added here.
- Adding `OpenAPINinjaClient`, which extends `ninja.testing.TestClient`
- Adding `GenericRequest` class and adapting schema tester to be compatible with both Django a Django Ninja test clients.
- Adding decorator for serializing `json` payloads for Django Test Client, as code was repetitive in each method.
> feat: adding support for Django Ninja test client

- openapi_tester/clients.py
- openapi_tester/exceptions.py
- openapi_tester/schema_tester.py
- tests/conftest.py
- tests/test_clients.py
- tests/test_django_ninja.py
As reported by @StopMotionCuber, after we introduced support for Django-Ninja's test client within the module `clients.py`, projects which doesn't have `ninja` installed began failing when attempting to import the former client.
This PR aims to fix this issue while defining an optional import and validation of the `ninja` library.
> fix: making import of ninja optional

- .pre-commit-config.yaml
- openapi_tester/clients.py
- openapi_tester/loaders.py
- openapi_tester/response_handler.py
- openapi_tester/utils.py
- openapi_tester/validators.py
- poetry.lock
- pyproject.toml
- tests/test_clients.py
- tests/test_django_ninja.py
- tests/test_openapi_object.py
- tests/test_utils.py
- Replacing the use of `json` with [orjson](https://github.com/ijl/orjson), which has proved to be [way more performant](https://github.com/ijl/orjson?tab=readme-ov-file#performance) than json when serializing / deserializing data.
-
- Updating `mirrors-mypy` version in `pre-commit` as it was very old and it started to fail in pipelines.
> Replace `json` with `orjson`

- openapi_tester/utils.py
- pyproject.toml
- tests/test_clients.py
As seen in the related issue, when performing a request without specifying the `content-type` as `application/json`, `serialize_json` decorator is skipping the serialization and eventually passing a dict while the framework's function will expect it already formatted as string.
This PR fixes this issue by defaulting `content_type` to `application/json` when it's not provided.
> fix: serializing request body when content type not provided

- openapi_tester/schema_tester.py
- pyproject.toml
- test_project/api/views/pets.py
- test_project/urls.py
- tests/schemas/openapi_v3_reference_schema.yaml
- tests/test_clients.py
- tests/test_django_framework.py
- tests/test_schema_tester.py
Validation of `writeOnly` properties is currently being applied for both requests and responses, being the later naturally wrong. When submitting both a request and a response share an object on the OpenAPI documentation, which have this `writeOnly` defined for a field, one get the following error on the request (as also seen in the example in the linked issue to this PR):
```
openapi_tester.exceptions.DocumentationError: The following property was found in the response, but is documented as being "writeOnly": "tag"
```
The validation should happen only for requests. This PR makes sure of so, adding an additional condition and additional tests for it
> fix: validating writeOnly properties only for responses

- openapi_tester/constants.py
- openapi_tester/schema_tester.py
- openapi_tester/utils.py
- tests/schemas/openapi_v3_reference_schema.yaml
- tests/test_clients.py
- tests/test_openapi_object.py
- tests/test_utils.py
Adding validation for requests which include a `readOnly` field.
> feat: readonly fields validation for requests

- openapi_tester/clients.py
The optional import of `django-ninja` is there because it's not mandatory to have it installed to have the package, as one could use it with DRF. However, it's not necessary to have a log entry informing this, given this is already logged when attempting to create an instance of `OpenAPINinjaClient`.  
This PR handles the previous described situation, by removing the log entry.
> chore: removing unnecesary log when django-ninja is not installed

- .github/workflows/testing.yml
Updating artifacts actions - See: https://github.com/orgs/community/discussions/142581
> fix: updating artifact actions versions as v3 was deprecated

- .pre-commit-config.yaml
- openapi_tester/response_handler.py
- openapi_tester/schema_tester.py
- openapi_tester/validators.py
- test_project/api/ninja/api.py
- test_project/api/ninja/schemas.py
- test_project/migrations/0001_initial.py
- tests/schemas/sample-schemas/observations.yaml
- tests/schemas/users_django_api_schema.yaml
- tests/test_django_ninja.py
- tests/test_validators.py
Within the current included `format` validations for each of the types defined, the two supported formats for `integer` values (`int32` and `int64`) are missing. 
Adding corresponding validations for these formats.
> feat: adding validation for int32 and int64 format in integer types

- openapi_tester/schema_tester.py
- openapi_tester/validators.py
- tests/test_schema_tester.py
- tests/test_validators.py
The proper validation for `null` type is not working when using `anyOf` and `oneOf`. 
Given that `null` is a defined [data type](https://spec.openapis.org/oas/v3.1.1.html#data-types) in OpenAPI 3.1.x, adding the proper validation for this type, and avoiding calling `test_is_nullable` when the schema under test is not OpenAPI 3.1.x.
> feat: adding proper 'null' type validation for openapi 3.1.x

- openapi_tester/schema_tester.py
- openapi_tester/validators.py
- tests/test_validator_errors.py
- tests/test_validators.py
- Adding proper validation for schemas with multiple types defined and multiple restrictions.
- Adding remaining validation scenarios for `null` type in OpenAPI 3.1.x
> Multiple types with multiple restrictions + `null` type remaining scenarios

- .github/workflows/testing.yml
- README.md
- openapi_tester/constants.py
- openapi_tester/response_handler.py
- openapi_tester/schema_tester.py
- openapi_tester/utils.py
- pyproject.toml
- test_project/api/ninja/api.py
- test_project/api/ninja/schemas.py
- tests/conftest.py
- tests/schemas/users_django_api_schema.yaml
- tests/test_django_ninja.py
- tests/test_openapi_query_params_object.py
- tests/test_schema_tester.py
- tests/test_utils.py
This PR implements query parameter validation for API requests.
Query parameters are a fundamental component of API requests and maintaining consistency between API documentation and implementation improves the developer experience and reliability of the API.
This helps to validate all query parameters used in the test suite (and implemented in the API) are properly documented and viceversa.
Note, that request validation is [only performed for scenarios with successful responses](https://github.com/maticardenas/django-contract-tester/blob/master/openapi_tester/clients.py#L45), this is to ensure the library does not interfer ewith all functional negative scenarios test cases. Nevertheless, for all successful scenarios validation will be performed, ensuring:
- Passed query parameters are …
> feat: adding request query parameters validation

- openapi_tester/schema_tester.py
- openapi_tester/utils.py
- tests/test_openapi_query_params_object.py
- tests/test_utils.py
Given that query parameters are received with `string` type within the request object for both DRF and Django Ninja, we performa normalization of the same, making them adquire the proper compatible value in order to validate them properly against the `type` defined in the OpenAPI specification.
Nevertheless, this make it challenging to validate that a query parameter is sent as proper `string` (given they are always like that in the object), causing validation issues like the ones described in the [related issue](https://github.com/maticardenas/django-contract-tester/issues/64).
This PR makes the changes to avoid performing a parameter validation when the `type` is defined as `string` (without format or contraints) in the OpenAPI specs.
> fix: avoid query params validation when type defined as string
